name: Сборка

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Подготовка окружения
        run: |
          sha=$(echo "${{ github.sha }}" | cut -c 1-7 | tr '[:upper:]' '[:lower:]')
          echo "sha=$sha" >> "$GITHUB_ENV"
          
          image_name=$(echo "${{ secrets.docker_username }}/${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "image_name=$image_name" >> "$GITHUB_ENV"
          
          image_tag=$(echo "${{ github.ref_name }}-$sha" | tr '[:upper:]' '[:lower:]')
          echo "image_tag=$image_tag" >> "$GITHUB_ENV"
      - name: Checkout репозитория
        uses: actions/checkout@v2
      - name: Установка JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt
      - name: Сборка программы
        run: javac Main.java
      - name: Сборка docker образа
        run: docker build -t "$image_name:$image_tag" .
      - name: Авторизация в Docker Hub
        run: docker login -u ${{ secrets.docker_username }} -p ${{ secrets.docker_password }}
      - name: Push образа в Docker Hub
        run: |
          echo "$image_name:$image_tag"
          docker push "$image_name:$image_tag"
          if [[ "${{ github.ref }}" == "refs/head/main" ]]; then
            docker tag "$image_name:$image_tag" "$image_name:latest"
            docker push "$image_name:latest"
          fi
