name: Сборка

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.prepare_env.outputs.image_tag }}

    steps:
      - name: Подготовка окружения
        id: prepare_env
        run: |
          if [ -n "${{ github.head_ref }}" ]; then
            branch=${{ github.head_ref }}
          else
            branch=${{ github.ref_name }}
          fi
          
          sha=$(echo "${{ github.sha }}" | cut -c 1-7 | tr '[:upper:]' '[:lower:]')
          
          echo "image_name=$image_name" >> "$GITHUB_ENV"
          
          image_tag=$(echo "$branch-$sha" | tr '[:upper:]' '[:lower:]')
          echo "image_tag=$image_tag" >> "$GITHUB_ENV"
          
          echo "image_tag=$image_tag" >> "$GITHUB_OUTPUT"
      - name: Checkout репозитория
        uses: actions/checkout@v2
      - name: Установка JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt
      - name: Сборка программы
        run: mvn install
      - name: Авторизация в Docker Hub
        run: docker login -u ${{ secrets.docker_username }} -p ${{ secrets.docker_password }}
      - name: Сборка docker образа converter
        run: |
          cd converter
          docker build -t "marattim/converter:$image_tag" .
          cd ..
      - name: Push образа converter в Docker Hub
        run: |
          echo "marattim/converter:$image_tag"
          docker push "marattim/converter:$image_tag"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker tag "marattim/converter:$image_tag" marattim/converter:latest
            docker push marattim/converter:latest
          fi
      - name: Сборка docker образа accounts
        run: |
          cd accounts
          docker build -t "marattim/accounts:$image_tag" .
          cd ..
      - name: Push образа accounts в Docker Hub
        run: |
          echo "marattim/accounts:$image_tag"
          docker push "marattim/accounts:$image_tag"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker tag "marattim/accounts:$image_tag" marattim/accounts:latest
            docker push marattim/accounts:latest
          fi

  autotest:
    needs: build_and_push
    uses: evevseev/the-bank-tests/.github/workflows/autotests-hw4.yml@main
    with:
      chart-path: ./helm
      converter-image-name: marattim/converter
      accounts-image-name: marattim/accounts
      image-tag: ${{ needs.build_and_push.outputs.image_tag }}
    secrets:
      HSE_LOKI_TOKEN: ${{ secrets.HSE_LOKI_TOKEN }}
