name: Сборка

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2
      - name: Сборка программы
        run: |
          javac Main.java
      - name: Сборка docker образа
        run: |
          image_name="${{ secrets.docker_username }}/${{ github.event.repository.name }}"
          image_tag="${{ github.ref }}-${{ github.sha:0:7 }}"
          docker build -t "$image_name:$image_tag" .
      - name: Авторизация в Docker Hub
        run: |
          docker login -u ${{ secrets.docker_username }} -p ${{ secrets.docker_password }}
      - name: Push образа в Docker Hub
        run: |
          docker push "$image_name:$image_tag"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker tag "$image_name:$image_tag" "$image_name:latest"
            docker push "$image_name:latest"
          fi
